export const panelTheme = {
  bg: "#f8f9fa",
  panel: "#ffffff",
  toolbar: "#f1f3f4",
  toolbarHover: "#e8eaed",
  border: "#dadce0",
  borderStrong: "#bdc1c6",
  text: "#202124",
  textSecondary: "#5f6368",
  textDisabled: "#9aa0a6",
  blue: "#1a73e8",
  blueBg: "#e8f0fe",
  blueDark: "#1557b0",
  green: "#188038",
  greenBg: "#e6f4ea",
  orange: "#e8710a",
  orangeBg: "#fce8d5",
  red: "#d93025",
  redBg: "#fce8e6",
  purple: "#9334e6",
  purpleBg: "#f3e8fd",
  sans: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, sans-serif',
  mono: '"Roboto Mono", Consolas, "Courier New", monospace',
  rowHover: "#f1f3f4",
  rowSelected: "#e8f0fe",
  switchOn: "#1a73e8",
  switchOff: "#dadce0",
};

export const logTypeColors = {
  SEND: { bg: panelTheme.blueBg, text: panelTheme.blue },
  MOCK: { bg: panelTheme.purpleBg, text: panelTheme.purple },
  EMIT: { bg: panelTheme.greenBg, text: panelTheme.green },
  WARN: { bg: panelTheme.orangeBg, text: panelTheme.orange },
  ERROR: { bg: panelTheme.redBg, text: panelTheme.red },
} as const;
